buxfix: set autocomplete attribute to api-key input
GaiZhenbiao/ChuanhuChatGPT pull request #1024
Opened 2024-01-05 16:49 UTC by stingshen

## 作者自述
### 描述

使用 new-password 作为 autocompletion 属性的值，以避免 chrome 显示密码自动提示框。

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password

before:

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/6214067/957eb73a-4915-4b4d-83f4-081bab8cf6d3)

after:

![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/6214067/f0ed4ccf-3b6d-48e6-9ff2-473cef9b5172)

### 相关问题
https://github.com/GaiZhenbiao/ChuanhuChatGPT/issues/1020

2024-01-05 17:06 UTC, MZhao-ouo commented
这个方法我们试过了，并不起作用😥
我刚刚拉了下pr，也还会弹出来

2024-01-05 17:19 UTC, MZhao-ouo reviewed
似乎真的有用

2024-01-05 19:49 UTC, Keldos-Li requested changes
似乎确实有用，但我不理解为什么改API key的反而使得这里model-select-dropdown的可以……是因为原先apikey input的autocomplete属性没有值吗？我不理解……直接设置model-select-dropdown的input的autocomplete值为new-password就不行……

2024-01-05 19:49 UTC, Keldos-Li commented on web_assets/javascript/ChuanhuChat.js
> +
函数和变量命名上为了避免歧义，我觉得还是应该在后面加个input，
function setAPIKeyInput()
apiKeyInput = ...

2024-01-05 20:37 UTC, Keldos-Li approved these changes

2024-01-06 04:03 UTC, GaiZhenbiao approved these changes

2024-01-06 04:04 UTC, merged

2024-01-15 09:59 UTC, FreedomXD commented
您好，我这边拉了新的代码，还有这个框，不知道是哪里出了问题
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/34237352/159ad979-0a08-49d3-9d4f-109f781c49b2)

2024-01-15 10:01 UTC, FreedomXD commented
您好，我拉了新的代码，但还有这个框，是哪里出了问题呢
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/34237352/78618f17-370e-44db-981a-9c950985528e)

2024-01-15 10:31 UTC, stingshen commented
> 您好，我拉了新的代码，但还有这个框，是哪里出了问题呢 ![image](https://private-user-images.githubusercontent.com/34237352/296720303-78618f17-370e-44db-981a-9c950985528e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTQ5NjMsIm5iZiI6MTcwNTMxNDY2MywicGF0aCI6Ii8zNDIzNzM1Mi8yOTY3MjAzMDMtNzg2MThmMTctMzcwZS00NGRiLTk4MWEtOWM5NTA5ODU1MjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwMzEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNmUzNGMxMjU3ZjkzZjdhY2Y5N2RkOTc4NmQ2ODhjZGMwNzIwNmRhNzk3MDE4OTM3NGJmOGRiY2ViNzMwMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g5RnZhVZuGoz7Sw2Ih7JZgb8iMlFHuDeUA-XNNBJr6I)

用 chrome inspect 看下 api-key input 的 autocomplete 值是什么？确认下代码生效了。

2024-01-15 11:57 UTC, FreedomXD commented
> api-key input 的 autocomplete 值是

还是off，确实没生效，这怎么回事呀

2024-01-15 12:23 UTC, Keldos-Li commented
@FreedomXD 确定拉取了最新的代码吗？或者我们这几天release一个新版本，应该就没问题了

2024-01-15 12:25 UTC, FreedomXD commented
> @FreedomXD 确定拉取了最新的代码吗？或者我们这几天release一个新版本，应该就没问题了

是最新的，我还进去看了代码，不知道咋回事

2024-01-15 12:45 UTC, Keldos-Li commented
> 是最新的，我还进去看了代码，不知道咋回事

那其他的js能生效吗？控制台有其他报错吗？那些按钮能按吗？

2024-01-15 13:12 UTC, FreedomXD commented
> > 是最新的，我还进去看了代码，不知道咋回事
> 
> 那其他的js能生效吗？控制台有其他报错吗？那些按钮能按吗？

看起来都是生效的，没有太多额外的报错，然后可见范围内的按钮都能按，我再查一下吧，不行就等你们的新版本release

2024-01-15 13:25 UTC, stingshen commented
> > > 是最新的，我还进去看了代码，不知道咋回事
> > 
> > 
> > 那其他的js能生效吗？控制台有其他报错吗？那些按钮能按吗？
> 
> 看起来都是生效的，没有太多额外的报错，然后可见范围内的按钮都能按，我再查一下吧，不行就等你们的新版本release

我这边重现了。我来看下。

2024-01-15 13:30 UTC, stingshen commented
> > > 是最新的，我还进去看了代码，不知道咋回事
> > 
> > 
> > 那其他的js能生效吗？控制台有其他报错吗？那些按钮能按吗？
> 
> 看起来都是生效的，没有太多额外的报错，然后可见范围内的按钮都能按，我再查一下吧，不行就等你们的新版本release

我这边本地确认了，没有问题。autocomplete 属性能生效。