History Call Function
GaiZhenbiao/ChuanhuChatGPT pull request #1142
Opened 2024-07-12 11:06 UTC by YangSierCode000

## Description
This pull request introduces the `#history_name` feature, which allows users to dynamically load specific conversation histories into the current chat session. This functionality is intended to enhance user interaction by enabling seamless reference to past discussions without leaving the context of the current conversation.

## Screenshots
<img width="808" alt="3f17ccfef6165ff2ac794f75a5329a5" src="https://github.com/user-attachments/assets/4f06a744-54a0-403d-889e-1a9d257ebc2f">

2024-07-12 11:12 UTC, YangSierCode000 commented
考虑创建其他历史记录的vector store，没想好怎么弄，感觉前端甚至是持久化存储都要改。

2024-07-12 11:23 UTC, Keldos-Li reviewed
需要还原对文件缩进和gitignore做的修改👀

2024-07-12 11:26 UTC, YangSierCode000 commented
> 需要还原对文件缩进和gitignore做的修改👀

我处理一下

2024-07-12 13:40 UTC, YangSierCode000 commented
加了一个开关，debug了load history部分。
![image](https://github.com/user-attachments/assets/221b96fb-e59d-4577-b1e5-d92954c73720)

2024-07-20 12:06 UTC, Keldos-Li requested changes
朋友，感谢你的贡献，川虎哥几日不在，我先谈谈我对这个功能的想法。

首先我认同这个功能，应该还是会有人有这种引用其他历史对话的需求，不过，用#号可能太常见了，可能容易和各种东西冲突，我现在个人的想法是参照其他双向链接的笔记软件的语法，用双方括号：`[[file_name]]`。

然后是页面显示上……辛苦你学着我们的写法加了一个开关qwq，但我想一方面这个功能不需要频繁开关，另一方面底下一条其实很短，放不太下这么多开关qwq，大概在config里写一个开启与否即可。

@GaiZhenbiao 你怎么看🥺

2024-07-21 05:47 UTC, YangSierCode000 commented
`[[file_name]]` 可以，可以，我没有用过类似的语法，这个如果符合使用习惯的话，没问题。然后，关于开关的问题，我当时也是考虑到 # 开头也挺常见的，所以我就想，如果说能加一个开关是不是最好。因为怎么说呢，加一个开关，你之后如果说需要这个功能，你打开；不需要这个功能，而且你开头是 # 的，你就可以关掉。而且现在的话，代码里面现在是默认开启。然后如果说是在 config 里面调整是否开闭的话，那么在界面上没有显示，会不会显得不那么 user-friendly 之类的。

2024-07-21 05:49 UTC, YangSierCode000 commented
`[[file_name]]` 可以，可以，我没有用过类似的语法，这个如果符合使用习惯的话，没问题。然后，关于开关的问题，我当时也是考虑到 # 开头也挺常见的，所以我就想，如果说能加一个开关是不是最好。因为怎么说呢，加一个开关，你之后如果说需要这个功能，你打开；不需要这个功能，而且你开头是 # 的，你就可以关掉。而且现在的话，代码里面现在是默认开启。然后如果说是在 config 里面调整是否开闭的话，那么在界面上没有显示，会不会显得不那么 user-friendly 之类的。

2024-07-21 06:23 UTC, Keldos-Li commented
输入框上方是为了频繁切换用的功能按钮，这个引用一般开了就开了，关了就关了，我认为算长期的，不需要占用寸土寸金的地方。如果想在页面中显示，可以放在此处：
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/29d267b9-465c-4c54-986f-a55beddfaee0">

2024-07-26 14:55 UTC, closed without merging

2024-07-26 14:56 UTC, YangSierCode000 commented
我稍后改一下