feat：修改讯飞大模型名称为“官网”对应名称；同时增加 Spark Pro-128K类型；
GaiZhenbiao/ChuanhuChatGPT pull request #1153
Opened 2024-08-20 01:28 UTC by ZhengQinyu

## 作者自述
### 描述
现有项目中，讯飞大模型以版本号为名称，和官方文档不一致，使用过程中难免有些困惑，所以建议修改为“官网”对应名称，参考官方链接 [讯飞接口说明-请求地址](https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)

v4.0 -> Spark4.0 Ultra
v3.5 -> Spark Max
v3.0 -> Spark Pro
。。。

同时新增 Spark Pro-128K模型

### 相关问题

#1136 

### 补充信息

1. 目前为了兼容旧的配置文件，还保留了旧的带版本的名称，可以看情况删除
2. 模型相关的配置，被我放到了 `placeholder` 字段，可以看情况做调整

2024-08-20 01:40 UTC, Keldos-Li requested changes
`placeholder`是当前没有对话时显示在聊天区块用来提示模型功能指引用户发起对话的占位部分，自定义程度较大，不适合作为在线模型本身域名路径存放的对应字段，为了保持统一我觉得path domain什么的可以直接加在METADATA里或者再加到一个新的字典键里面之类的？

2024-08-20 01:50 UTC, ZhengQinyu commented
> `placeholder`是当前没有对话时显示在聊天区块用来提示模型功能指引用户发起对话的占位部分，自定义程度较大，不适合作为在线模型本身域名路径存放的对应字段，为了保持统一我觉得path domain什么的可以直接加在METADATA里或者再加到一个新的字典键里面之类的？

我看到有个‘metadata’字段，之前没注意到，放的是 `additional metadata for the model`，我调整成放这里吧？或者交给你你合并后再调整？
因为我还保留了旧的配置，这个对部分已经使用中的开发者来说，需要修改配置文件才能使用，这个也需要你考虑是删除还是保留。

2024-08-21 05:22 UTC, Keldos-Li reviewed
唔，这不是我的本意，我本来想的是,比如直接
```
"spark xxx": {
    "domain": "....",
    "path": "...."
}
```
而不再套一层什么了。

不过还是问问川虎哥 @GaiZhenbiao 👀

2024-08-21 05:47 UTC, GaiZhenbiao approved these changes

2024-08-21 05:47 UTC, merged