English Version
GaiZhenbiao/ChuanhuChatGPT pull request #53
Opened 2023-03-07 04:57 UTC by Haste171

A fully English version of this project for a majority of users.

2023-03-07 05:03 UTC, GaiZhenbiao commented
有没有可能做成动态的，根据系统语言切换中英文？如果做不到，最好单独放一个英文版文件。
另外readme能不能也翻译一下？🤔

2023-03-07 05:06 UTC, Haste171 commented
是的，README文件也可以翻译。

现在为了简单起见，最好单独准备一个英文版本的文件。

2023-03-07 05:09 UTC, Haste171 reviewed
New english version

2023-03-07 05:57 UTC, GaiZhenbiao requested changes
中文python文件应该改回去。
Tuchuan Tiger……这是GPT翻译的吧😂应该是Tuchuan Huhuhu
Please input your OpenAI API key here...这句话怪怪的
Unnamed conversation history 应该是Untitled
Please input here. 应该是Type here...之类。不应该用Input。上面那个Input也应该改
Reading Template 不应该加ing
text box 不应该有空格
Changing share=True 应该是set
Customizable port 应该是port customizable

2023-03-12 03:55 UTC, GaiZhenbiao commented
由于长期没有收到回应，且main分支代码已经产生了比较大的变化，因此关闭该Pr。欢迎再次提交。

2023-03-12 03:55 UTC, closed without merging