doc: Update docs for ChuanhuChat v5.0
GaiZhenbiao/ChuanhuChatGPT pull request #887
Opened 2023-09-14 16:20 UTC by MZhao-ouo

ChuanhuChat v5.0 has many updates, and we need to update the readme. Can you please help us check if the translation of the README in your language is appropriate?👀 @bropines @ina111

2023-09-14 16:55 UTC, Keldos-Li commented
If you have time, you can also check whether the string translation in ja_JP.json and ru_RU.json is appropriate (you can pull and run the latest code on main branch to see if the text on the page conforms to semantics, or whether there are characters beyond the container boundary, etc.). Thank you very much! 🥹

2023-09-14 22:52 UTC, bropines commented
> ChuanhuChat v5.0 has many updates, and we need to update the readme. Can you please help us check if the translation of the README in your language is appropriate?👀 @bropines @ina111

I checked and corrected ReadMe a little, and also added Russian to presets.py, and of course, with all the changes, I created a PR. As for the interface, there are only issues with the text input fields, but I think this is a minor detail.
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/57861007/6dd402c4-bdfd-48ec-b330-f0caf5682103)
![image](https://github.com/GaiZhenbiao/ChuanhuChatGPT/assets/57861007/d202c9fd-6f4e-43ed-986e-c5e61ae477c2)


I would also like to ask (so as not to change gitignore) to download the promt template in Russian.
Just rename to .json
[Russian_prompts.txt](https://github.com/GaiZhenbiao/ChuanhuChatGPT/files/12614151/Russian_prompts.txt)

2023-09-15 05:12 UTC, MZhao-ouo commented
> > ChuanhuChat v5.0 has many updates, and we need to update the readme. Can you please help us check if the translation of the README in your language is appropriate?👀 @bropines @ina111
> 
> I would also like to ask (so as not to change gitignore) to upload the promt template in Russian. Just rename to .json [Russian_prompts.txt](https://github.com/GaiZhenbiao/ChuanhuChatGPT/files/12614151/Russian_prompts.txt)

Maybe you can submit a request to main directly. It's not a risky change.

2023-09-15 05:35 UTC, GaiZhenbiao commented
I added it in https://github.com/GaiZhenbiao/ChuanhuChatGPT/commit/5d96469f54fe08a359caee9f94f30d50bd4a9edd

2023-09-15 06:19 UTC, Keldos-Li commented on readme/README_ru.md
> +- В поле ввода можно использовать клавиши <kbd>↑</kbd> и <kbd>↓</kbd>, чтобы быстро переключаться в истории отправки;
So shall we use the `< kbd >` tag or the `< code >` tag next?

2023-09-15 08:34 UTC, Keldos-Li requested changes
我再找人看看

2023-09-15 08:34 UTC, Keldos-Li commented on readme/README_ja.md
>  ## 使う上でのTips
这一部分是不是要删掉

2023-09-15 08:34 UTC, Keldos-Li commented on readme/README_ja.md
> +<sup>新!</sup> Finetune（微調整）GPT 3.5に対応！
上面和下面统一用 新！ 或者 New！吧？

2023-09-15 08:35 UTC, Keldos-Li commented on readme/README_ja.md
>  ## 使う上でのTips
额，这里引用的位置有问题，应该是

使う上でのTips 这个段落

https://github.com/GaiZhenbiao/ChuanhuChatGPT/blob/570a39dfcef05380ace6015c03e5ad9c5281e026/readme/README_ja.md?plain=1#L120-L129

2023-09-16 05:17 UTC, merged